# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required

os:
  - linux
julia:
  - 0.6
notifications:
  email: false

after_success:
- echo $TRAVIS_JULIA_VERSION
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e 'run(`lualatex -v`)'
- julia -e 'Pkg.clone(pwd())'
- julia -e 'Pkg.add("RobotOS.jl")'
- julia -e 'Pkg.add("Documenter");'
- julia -e 'cd(Pkg.dir("RobotOSDocs"));ENV["DOCUMENTER_DEBUG"]=true; include(joinpath("docs", "make.jl"))'
