# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      sudo: required
      julia: 0.6
notifications:
  email: false
after_success:
- julia -e 'Pkg.add("Documenter");'
- julia -e 'cd(Pkg.dir("AVExamples"));ENV["DOCUMENTER_DEBUG"]=true; include(joinpath("docs", "make.jl"))'
